baseURL = "https://zls0725.github.io/"
title = "香港Henry"
theme = "blowfish"

defaultContentLanguage = "zh-cn"
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    weight = 1
    title = "亨利的博客"
    languageCode = "zh-cn"
    isoCode = "zh-CN"
    params.displayName = "简"
    params.dateFormat = "2006年1月2日"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Henry's Blog"
    languageCode = "en"
    isoCode = "en"
    params.displayName = "EN"
    params.dateFormat = "2 January 2006"

  [languages.es]
    languageName = "Español"
    weight = 3
    title = "Blog de Henry"
    languageCode = "es"
    isoCode = "es-ES"
    params.displayName = "ES"
    params.dateFormat = "2 de enero de 2006"
