zh:
  languageName: "简体中文"
  weight: 1
  contentDir: "content/zh"
  languageCode: "zh-CN"
  title: "香港Henry的博客"
  description: "这是我的中文博客，分享技术与生活"
  params:
    homeSubtitle: "欢迎来到我的博客"
    dateFormat: "2006年01月02日"

en:
  languageName: "English"
  weight: 2
  contentDir: "content/en"
  languageCode: "en-US"
  title: "Hong Kong Henry's Blog"
  description: "A blog about tech and life"
  params:
    homeSubtitle: "Welcome to my blog"
    dateFormat: "January 2, 2006"

es:
  languageName: "Español"
  weight: 3
  contentDir: "content/es"
  languageCode: "es-ES"
  title: "Blog de Hong Kong Henry"
  description: "Un blog sobre tecnología y vida"
  params:
    homeSubtitle: "Bienvenido a mi blog"
    dateFormat: "2 de enero de 2006"
