baseURL = "https://zls0725.github.io/"
languageCode = "zh-cn"
title = "香港Henry"
enableRobotsTXT = true
theme = "blowfish"
defaultContentLanguage = "zh-cn"

[params]
  displayName = "Henry"
  dateFormat = "2006年1月2日"
  showReadingTime = true
  showWordCount = true

[params.homepage]
  layout = "list"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  layoutBackgroundBlur = true

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 1

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    weight = 1
    title = "亨利的博客"
    languageCode = "zh-cn"
    isoCode = "zh-CN"
    params.displayName = "简"
    params.dateFormat = "2006年1月2日"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Henry's Blog"
    languageCode = "en"
    isoCode = "en"
    params.displayName = "EN"
    params.dateFormat = "2 January 2006"


  [module.hugoVersion]
    extended = true
    min = "0.141.0"
    max = "0.149.0"

publishDir = "public"
