# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://zls0725-github-io.pages.dev

# 加载模块化配置
configDir = "config/_default"

[params.header]
  showLanguageSwitcher = true


theme = "blowfish"                          # 使用 Blowfish 主题
baseURL = "https://zls0725-github-io.pages.dev"         # 本地开发地址，部署时请改为正式域名
defaultContentLanguage = "zh"              # 默认语言设置为中文
defaultContentLanguageInSubdir = false
disableLanguages = []                     # 不禁用任何语言，方便翻译工作上线

# pluralizeListTitles = "true"             # Hugo 的复数化功能，适用于非英语语言

enableRobotsTXT = true                     # 启用 robots.txt，有助于 SEO
summaryLength = 30                         # 自动摘要最大词数
hasCJKLanguage = true                      # 启用中日韩语言支持（适合中文分词）

buildDrafts = false                        # 不构建草稿内容
buildFuture = false                        # 不构建未来发布日期的内容

enableEmoji = true                         # 支持 Emoji 表情

googleAnalytics = "G-PEDMYR1V0K"           # Google Analytics 跟踪代码

[pagination]
  pagerSize = 102                          # 每页显示内容数量

[imaging]
  anchor = 'Center'                        # 图像处理时的锚点位置（居中）

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'                    # 网站地图中内容更新频率
  filename = 'sitemap.xml'                # 网站地图文件名
  priority = 0.5                           # 网站地图中页面的优先级

[outputs]
  home = ["HTML", "RSS", "JSON"]          # 首页输出格式：HTML 页面、RSS 订阅、JSON 数据

[related]
  threshold = 0                            # 相关内容的匹配阈值（0 表示全部显示）
  toLower = false                          # 是否将关键词转换为小写（false 保持原样）

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "series"
    weight = 50

  [[related.indices]]
    name = "authors"
    weight = 20

  [[related.indices]]
    name = "date"
    weight = 10

  [[related.indices]]
    applyFilter = false
    name = 'fragmentrefs'
    type = 'fragments'
    weight = 10

# Render only specific parts of the site for faster development. 
# Note that there are more files are ignored in development/hugo.toml
#
# Usage: `hugo --renderSegments core` or `hugo --renderSegments core,en_only`
[segments]
  [segments.core]
    [[segments.core.includes]]
      # Debug core pages
      path = '{/,/docs,/docs/**,/samples,/samples/**}'
  [segments.en_only]
    [[segments.en_only.includes]]
      # Alternatively, you can use environment variable
      #   - UNIX: HUGO_DISABLELANGUAGES='it ja zh-cn' npm run example:core
      #   - Windows CMD: set "HUGO_DISABLELANGUAGES=it ja zh-cn" && npm run example:core
      #   - Windows PowerShell: $env:HUGO_DISABLELANGUAGES="it ja zh-cn"; npm run example:core
      lang = 'en'

# -- 多语言配置 --

[languages]

  [languages.zh]
    languageName = "简体中文"
    weight = 1
    contentDir = "content/zh"
    languageCode = "zh-CN"
    title = "香港Henry的博客"
    description = "这是我的中文博客，分享技术与生活"

    [languages.zh.params]
      homeSubtitle = "欢迎来到我的博客"
      dateFormat = "2006年01月02日"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    languageCode = "en-US"
    title = "Hong Kong Henry's Blog"
    description = "A blog about tech and life"

    [languages.en.params]
      homeSubtitle = "Welcome to my blog"
      dateFormat = "January 2, 2006"

  [languages.es]
    languageName = "Español"
    weight = 3
    contentDir = "content/es"
    languageCode = "es-ES"
    title = "Blog de Hong Kong Henry"
    description = "Un blog sobre tecnología y vida"

    [languages.es.params]
      homeSubtitle = "Bienvenido a mi blog"
      dateFormat = "2 de enero de 2006"
