name: Deploy Hugo to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0 # 确保拉取完整历史和子模块
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.134.2'
          extended: true
      - name: Check Submodules
        run: |
          git submodule update --init --recursive
          ls -la themes/
      - name: Build
        run: hugo --minify -D
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
      - name: Debug
        if: failure()
        run: |
          echo "Build failed. Checking public directory:"
          ls -la public/
          echo "Checking Hugo config:"
          cat config.toml
