name: Deploy Hugo to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.134.2'
          extended: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          [ -f package.json ] && npm ci || { npm init -y && npm install postcss postcss-cli autoprefixer --save-dev; }
      - name: Build
        run: hugo --minify -D
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
      - name: Debug
        if: failure()
        run: |
          echo "Build failed:"
          ls -la public/ || echo "Public directory not found"
          cat config.toml || echo "config.toml not found"
