name: Deploy Hugo to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.134.2'
          extended: true
      - name: Check Submodules
        run: |
          echo "Checking submodules..."
          git submodule update --init --recursive || echo "No submodules found or failed to initialize"
          ls -la themes/ || echo "Themes directory not found"
      - name: Install Node.js (for Blowfish SCSS)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: hugo --minify -D
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
      - name: Debug
        if: failure()
        run: |
          echo "Build failed. Checking public directory:"
          ls -la public/ || echo "Public directory not found"
          echo "Checking Hugo config:"
          cat config.toml || echo "config.toml not found"
          echo "Checking themes directory:"
          ls -la themes/ || echo "Themes directory not found"
